/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_sistemas_ovasistemaso_service_NativeSJF */

#ifndef _Included_com_example_sistemas_ovasistemaso_service_NativeSJF
#define _Included_com_example_sistemas_ovasistemaso_service_NativeSJF
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_sistemas_ovasistemaso_service_NativeSJF
 * Method:    scheduleSJF
 * Signature: ([I[I[I)[I
 */
JNIEXPORT jintArray JNICALL Java_com_example_sistemas_ovasistemaso_service_NativeSJF_scheduleSJF
  (JNIEnv *, jobject, jintArray, jintArray, jintArray);

#ifdef __cplusplus
}
#endif
#endif
