services:
  ova-sistemas:
    image: alejohernandez/ova-sistemas:latest
    container_name: ova-sistemas
    ports:
      - "8080:8080"
    profiles:
      - app
    networks:
      - red-backend-app

networks:
  red-backend-app:
    driver: bridge
